feat: unchecked collateral withdraw
kreskohq/kresko-protocol pull request #70
Opened 2023-04-28 23:12 UTC by zbirenbaum

Implements DEV-38 - unchecked collateral withdraw

2023-04-29 17:06 UTC, panukettu commented on src/contracts/minter/facets/DepositWithdrawFacet.sol
> +        ms().verifyAccountCollateral(_account, _collateralAsset, _withdrawAmount);
`_withdrawAmount` should be 0 here as we already reduce deposits in `recordCollateralWithdrawal`

2023-04-29 17:06 UTC, panukettu commented on src/contracts/minter/facets/DepositWithdrawFacet.sol
> +        (bool success, bytes memory data) = Meta.msgSender().call(
will be much simpler if we just inline this after the interface exists

2023-04-29 17:34 UTC, panukettu commented
> Implements DEV-38 - unchecked collateral withdraw
> 
> A couple things left to do here so marked it as a draft, but wanted to get the core implementation up so it could be discussed.
> 
> I think we need an Interface for contracts which implement `onUncheckedCollateralWithdraw`
> 
> Is the AMM helper the only contract planned to use this, or should there be a IUncheckedCollateralHelper which the AMM helper inherits from?
> 
> Right now I call the function directly using low level calls, but standardizing this would probably be best.
> 
> Sorry in advance if this didn't use the linear integrations properly, I was having a little trouble with it.

1. Yes lets create a simple interface for a receiver eg. `ICollateralReceiver`. We could use `ERC165.supportsInterface` to ensure this on the function but not sure if that is overdoing it. 

2. This is generic. Contracts using this will use `IKresko.withdrawCollateralUnchecked` and implement `ICollateralReceiver.onUncheckedColalteralWithdraw`. No need for other considerations.

2023-05-02 15:26 UTC, zbirenbaum commented
I resolved all the issues in the comments, this should be ready for final review.

2023-05-02 15:54 UTC, tabshaikh commented
would love to see some tests the function

2023-05-02 15:54 UTC, tabshaikh commented on testbroke.sh
> +hh test src/test/minter/00-init.ts src/test/minter/01-configuration.ts src/test/oracle/* --deploy-fixture
maybe this whole file can be removed

2023-05-02 16:01 UTC, zbirenbaum commented on testbroke.sh
> +hh test src/test/minter/00-init.ts src/test/minter/01-configuration.ts src/test/oracle/* --deploy-fixture
`git add .` strikes again

2023-05-02 16:04 UTC, zbirenbaum commented
> would love to see some tests for this change

I thought about that too but was thinking they might belong thematically in the tests for something implementing ICollateralReceiver like the AMM Helper to make sure it can't withdraw too much, and that after it does something with the collateral that the user's MCR check still passes. Implementing a contract that can properly make use of this function would require actually doing something with the user's collateral.

2023-05-02 17:33 UTC, panukettu requested changes
It is looking good overall but lets scope this down a bit: Drop access without `Role.MANAGER` and remove mutex.  
We need to demonstrate few scenarios with tests as @tabshaikh suggested. Lets demonstrate following (at least):

1. Can do nothing after withdrawing some collateral in the receiver.
2. Can re-deposit withdrawn collateral back into the protocol.
3. Can deposit another collateral into the protocol for `_account` from the receiver.
4. Reverts because account ends up below MCR after callback.
5. Reverts because withdrawal amount is greater than account deposits. 
6. Reverts because caller is not `Role.MANAGER`.

2023-05-04 07:20 UTC, zbirenbaum commented
> * Can do nothing after withdrawing some collateral in the receiver if above MCR after callback.
> * Can re-deposit withdrawn collateral back into the protocol for `_account`.
> * Can deposit another collateral into the protocol for `_account`.
> * Reverts because account ends up below MCR after callback.
> * Reverts because withdrawal amount is greater than account deposits.
> * Reverts because caller is not `Role.MANAGER`.

I got a little stuck on trying to implement a `MockCollateralReceiver` contract. I looked at the other facet contracts for a while but still couldn't quite figure out exactly what it should be inheriting. It doesn't look like other facets have to be initialized but I'm not sure how I should be resolving the address of the Diamond proxy. Could you point me in the right direction or link contract(s) that require the some or all of the same basic protocol information as what is required here?

2023-05-09 12:08 UTC, panukettu commented
LGTM!

2023-05-09 12:37 UTC, merged